### ISSUE TITLE
animaly husbandry v13b

### ISSUE THREAD

**Issue by gamingoninsulin** [bnema/AnimalHusbandry_Eco#11]
i got this on eco version 0.9.7.13

`[08:02:23] Failed to start the server. Exception was Exception: Exception
Message:E:\SteamLibrary\steamapps\common\Eco Server\Mods\UserCode\animal husbandry\FreshMilk.cs(27,26): error CS1715: 'FreshMilkItem.BaseShelfLife': type must be 'float' to match overridden member 'FoodItem.BaseShelfLife'
Source:Eco.ModKit

System.Exception: E:\SteamLibrary\steamapps\common\Eco Server\Mods\UserCode\animal husbandry\FreshMilk.cs(27,26): error CS1715: 'FreshMilkItem.BaseShelfLife': type must be 'float' to match overridden member 'FoodItem.BaseShelfLife'
   at Eco.ModKit.RoslynCompiler.HandleCompilerError(ImmutableArray`1 diagnostics)
   at Eco.ModKit.RoslynCompiler.Compile(AssemblyLoadContext assemblyContext)
   at Eco.ModKit.RoslynCompiler..ctor(AssemblyLoadContext assemblyContext, String modsDirectory, String modsAssemblyPath)
   at Eco.ModKit.RoslynCompiler..ctor(String modsDirectory, String modsAssemblyPath)
   at Eco.ModKit.ModKitPlugin..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
Outer Exceptions:
Exception has been thrown by the target of an invocation.`

**Comment by gamingoninsulin** [comment]
after updating int to float for some files i get in lure sheep.cs(38,36) sheepitem does not exist
